#!/bin/bash

for FILENAME in $@; do
  FIRST_LINE="//===--- $FILENAME "
  FIRST_LINE_LEN=${#FIRST_LINE}
  for ((i = 0; i < 73 - $FIRST_LINE_LEN; ++i)); do
    FIRST_LINE+=-
  done
  FIRST_LINE+="===//"
  HEADER="$FIRST_LINE\n\
// Copyright (c) 2017 Nathan Forbes\n\
//\n\
// Licensed under the Apache License, Version 2.0 (the \"License\");\n\
// you may not use this file except in compliance with the License.\n\
// You may obtain a copy of the License at\n\
//\n\
//     http://www.apache.org/licenses/LICENSE-2.0\n\
//\n\
// Unless required by applicable law or agreed to in writing, software\n\
// distributed under the License is distributed on an \"AS IS\" BASIS,\n\
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n\
// See the License for the specific language governing permissions and\n\
// limitations under the License.\n\
//===--------------------------------------------------------------------===//\n"
  CONTENTS=`cat $FILENAME`
  echo -e "$HEADER\n$CONTENTS" > "$FILENAME.temp"
  if [ $? -eq 0 ]; then
    rm -f $FILENAME
    mv "$FILENAME.temp" $FILENAME
  fi
done
