#!/bin/bash

EXEC_NAME=jig
TARGET=
BUILD_DIR=
BUILD_TYPE=

if [ "$1" = "--clean" ]; then
  rm -rf build-debug build-release $EXEC_NAME-debug $EXEC_NAME-release
  exit 0
elif [ "$1" = "--debug" ]; then
  TARGET="$EXEC_NAME-debug"
  BUILD_DIR=build-debug
  BUILD_TYPE=Debug
else
  TARGET="$EXEC_NAME-release"
  BUILD_DIR=build-release
  BUILD_TYPE=Release
fi

mkdir $BUILD_DIR && \
  cd $BUILD_DIR && \
  cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && \
  make && \
  cd .. && \
  cp $BUILD_DIR/$EXEC_NAME ./$TARGET
